title: Sam Malawy's Portfolio of Cybersecurity Projects
description: This is to showcase my experience with defensive cybersecurity concepts and tools.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
